[tool.poetry]
name = "datagen"
version = "0.1.0"
description = ""
authors = ["Sanjaya Subedi <jangedoo@gmail.com>"]
readme = "README.md"
packages = [{include = "datagen"}]

[tool.poetry.dependencies]
python = "^3.11"
datasets = "^2.21.0"
pandas = "^2.2.2"
click = "^8.1.7"
openai = "^1.42.0"
python-dotenv = "^1.0.1"
litellm = "^1.74.3"
tomli-w = "^1.2.0"
jinja2 = "^3.1.6"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
rope = "^1.13.0"
black = "^24.8.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
datagen = "datagen.__main__:cli"