dataset_name = "Sentence Triplets Dataset"
description = "Sentence triplets (anchor, positive, negative pairs) in Nepali. "
authors = ["Sanjaya Subedi <jangedoo@gmail.com>"]
generation_output_dir = "../raw_data/ne_nli_triplets"
generation_logging_steps = 100

[sources.sentences]
path = "sentence-transformers/all-nli"
subset = "triplet"
split = "train"

[models."gpt-4-mini"]
backend = "openai"

[models."gpt-4-mini".params]
model = "gpt-4.1-mini"
temperature = 0.7
max_tokens = 2000

[models.gpt_oss]
backend = "openai"

[models.gpt_oss.params]
model = "gpt-oss:20b"
max_tokens = 2000
api_base = "http://localhost:11434/v1"
api_key = "abc"


[models.gemma3]
backend = "openai"

[models.gemma3.params]
model = "gemma3:12b"
max_tokens = 2000
api_base = "http://localhost:11434/v1"
api_key = "abc"

[generator]
generator = "templated"

[generator.params]
default_model = "gemma3"

default_system_prompt = """\
You are an expert at creating sentence similarity datasets. Given a triplet of anchor, positive and negative in English, you should translate them to Nepali.
"""

default_prompt_template = """\
Anchor Sentence: {{ input.input_sentence }}
Positive Sentence: {{ input.positive }}
Negative Sentence: {{ input.negative }}
"""

source_datasets = [{ name = "sentences", max_records = 10, shuffle = true }]

structured_output_schema = """\
from pydantic import Field

class TripletResponse(BaseModel):
    anchor: str = Field(description="Translated version of the input anchor sentence")
    positive_sentence: str = Field(description="Translated version of input positive sentence")
    negative_sentence: str = Field(description="Translated version of input negative sentence")
"""

output_template = """\
{
    "anchor": "{{ llm_output.anchor}}",
    "positive": "{{ llm_output.positive_sentence }}",
    "negative": "{{ llm_output.negative_sentence }}",

    "anchor_en": "{{ input.input_sentence}}",
    "positive_en": "{{ input.positive }}",
    "negative_en": "{{ input.negative }}"
}
"""

# Define aliases for the sentences dataset (moved to end)
[[generator.params.aliases]]
source = "sentences"
column_map = { input_sentence = "anchor" }


[curator.params]
upload_to_hf = false
upload_repo_id = "jangedoo/nepali-nli-triplets"
train_test_split = true
update_card = true
language = ["en", "ne"]
license = "mit"
task_categories = []
task_ids = []
